export default function() {
  this.transition(
    this.fromRoute('index'),
    this.use('crossFade'),
    this.reverse('crossFade')
  );
  this.transition(
    this.fromRoute('contacts'),
    this.toRoute('tasks'),
    this.use('toUp'),
    this.reverse('toDown')
  );
  this.transition(
    this.toRoute('contact.index'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('contact.calls'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('contact.details'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('contact.sales'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('contact.tags'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('contact.interview'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('contact.logs'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.toRoute('task'),
    this.use('toLeft'),
    this.reverse('toRight')
  );
  this.transition(
    this.hasClass('change-description'),
    this.toValue(true),
    this.use('scale')
  );
}
